### ISSUE TITLE
Support additional methods of database specification

### ISSUE THREAD

**Issue by docktermj** [Senzing/governor-postgresql-transaction-id#11]
**Is your feature request related to a problem? Please describe.**
Currently `SENZING_GOVERNOR_DATABASE_URLS` is used to specify databases to monitor.

The Governor should look for database information in the following places in the following order (i.e. first one wins):

1. `SENZING_GOVERNOR_DATABASE_URLS`
1. `SENZING_DATABASE_URL`
1. `SENZING_ENGINE_CONFIGURATION_JSON`

This is a follow-on task to https://github.com/Senzing/docker-init-container/issues/77

**Comment by jeffadair** [comment]
Covered by #12
