### ISSUE TITLE
Reduce outages due to XID exhaustion

### ISSUE THREAD

**Issue by brianmacy** [Senzing/governor-postgresql-transaction-id#20]
Have the governor help the system "back off" based on what auto-vacuum can keep up with.

As it crosses the threshold of the low water mark towards the high one, it should start an increasing pause between records.  Something like:
>10% - .01s, >20% - .1s, >40% - 1s, >80% - 10s

Then have the governor recheck every minute to see if it needs to adjust the delay.  The logging should say what, if any delay, is in effect.  And there may be some additional things desired to reduce logging, like only log every 10minutes unless the pause changes... or something that doesn't cause this change to dramatically increase logging.

**Comment by docktermj** [comment]
@ron  I'm doing a preliminary assignment of this to you.  I think this is the kind of problem you like solving.  ...and I just didn't want to forget over our vacations.

When we work on after the holidays, I'll fill you in with background.

**Comment by jamietypovsky** [comment]
We should change the defaults to the Governor per Brian.

**Comment by roncewind** [comment]
This has been done for quite awhile.  I believe Brian was going to test it?

**Comment by roncewind** [comment]
PR merged
