### ISSUE TITLE
f-strings not preferred?

### ISSUE THREAD

**Issue by roncewind** [Senzing/governor-postgresql-transaction-id#37]
pylint reports:
```senzing_governor_tester.py:79:4: W1203: Use lazy % or .format() formatting in logging functions (logging-fstring-interpolation)```

for
```
logging.info(f'wm: 510_000_000  wait_time={governor.get_wait_time(510_000_000)}')
```

why?  I thought f-strings were preferred?  is this rule right?

**Comment by docktermj** [comment]
Fixed via https://github.com/Senzing/governor-postgresql-transaction-id/issues/20
