### ISSUE TITLE
Postgres Governor returns incorrect wait time

### ISSUE THREAD

**Issue by glennjdea** [Senzing/governor-postgresql-transaction-id#53]
As I understand it, the postgres governor is supposed to return a number of seconds that clients should wait, or -1 if processing should be paused entirely. This is intended to avoid problems related to transaction ID wraparound. The governor iterates through the databases (https://raw.githubusercontent.com/Senzing/governor-postgresql-transaction-id/main/senzing_governor.py), computes a wait time for each, and returns a wait time to the client. In our case the penultimate database is approaching xid wraparound so a a wait time of -1 is assigned to old_wait_time (https://raw.githubusercontent.com/Senzing/governor-postgresql-transaction-id/main/senzing_governor.py). The next db is not approaching xid wraparound, and because old_wait_time !=0 it sets old_wait_time to 0 (https://github.com/Senzing/governor-postgresql-transaction-id/blob/main/senzing_governor.py#L406), which is then returned to the client. Perhaps it was thought that the old_wait_time was computed for the same database (in which case it would be ok to reset it to 0)? In any case, the result is that the client is not told to wait when it should be. Is this a bug?

**Comment by docktermj** [comment]
@glennjdea We've created a new 1.0.10 version that should correct the issue that you are seeing.  If it satisfies your concerns,  please close this issue.   If not, let us know what else is needed.

**Comment by docktermj** [comment]
Hi @glennjdea !

I hope the fix worked for you.   If it did please close this issue.

We'll go ahead and close this issue in a week, if we don't hear back from you.

**Comment by glennjdea** [comment]
Hi @docktermj .  We're no longer using the postgres governor, so I haven't tested your fix but am very happy to close the issue.  Thanks for your help.
